"""add banks table

Revision ID: 003
Revises: 002_seed
Create Date: 2025-11-08 22:07:05.137445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002_seed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external', sa.Boolean(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('api_user', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    # ### end Alembic commands ###
