"""add unique constraint virtual balance

Revision ID: 010
Revises: 009
Create Date: 2025-11-15 21:42:14.914447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010'
down_revision = '009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='ID клиента (team025-x)'),
    sa.Column('account_number', sa.String(length=20), nullable=False, comment='Номер счета'),
    sa.Column('account_type', sa.String(length=50), nullable=True, comment='Тип счета'),
    sa.Column('calculation_type', sa.String(length=50), nullable=True, comment='Тип вычисления баланса'),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True, comment='Баланс'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='Валюта'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Статус'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Время обновления'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('virtual_balance_bank_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='ID клиента (team025-x)'),
    sa.Column('bank_id', sa.Integer(), nullable=False, comment='ID банка'),
    sa.Column('target_share', sa.Numeric(precision=5, scale=2), nullable=False, comment='Доля в % от общей суммы ДС клиента'),
    sa.Column('account_type', sa.String(length=50), nullable=True, comment='Тип счета'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'bank_id', 'account_type', name='uq_virtual_balance_client_bank_account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_balance_bank_allocations')
    op.drop_table('virtual_accounts')
    # ### end Alembic commands ###
